spring:
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/labsdb?useSSL=false&serverTimezone=UTC
    username: root
    password: DaiMneSil1
  application:
    name: shnurok.lab2